// <auto-generated />
namespace TestAuth2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class JustTestMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JustTestMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202206271535269_JustTestMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
