// <auto-generated />
namespace TestAuth2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitMirations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitMirations));
        
        string IMigrationMetadata.Id
        {
            get { return "202206231418152_InitMirations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
